ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    print_diagnostics: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /ostem/steering_odom
    odom0_config: [false, false, false,
                   false, false, false,
                    true,  true, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    imu0: /ostem/imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                   true,  true,  true,
                  false, false, false]
    imu0_differential: true
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    print_diagnostics: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: /ostem/steering_odom
    odom0_config: [false, false, false,
                   false, false, false,
                    true, false, false,
                   false, false,  true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: true
    odom0_relative: false

    odom1: /ostem/odom/gps
    odom1_config: [true,  true, false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_queue_size: 10
    odom1_differential: false
    odom1_relative: false

    imu0: /ostem/imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                   true,  true,  true,
                  false, false, false]
    imu0_differential: true
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

navsat_transform:
  ros__parameters:
    frequency: 1.0
    delay: 3.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false