<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ostem">

    <!-- Constants -->
    <xacro:property name="chassis_length" value="0.410" />
    <xacro:property name="chassis_breadth" value="0.450" />
    <xacro:property name="chassis_height" value="0.005" />
    <xacro:property name="chassis_mass" value="5.132" />

    <xacro:property name="wheel_length" value="0.043" />
    <xacro:property name="wheel_radius" value="0.05035" />
    <xacro:property name="chassis_wheel_x_offset" value="${(chassis_length/2)-0.08}" />
    <xacro:property name="chassis_wheel_offset_height" value="0.009" />

    <xacro:property name="wheel_separation" value="0.529526" />
    <xacro:property name="wheel_mass" value="0.1" />

    <!-- Imports -->
    <xacro:include filename="materials.xacro" />

    <!-- Wheel xacro -->
    <xacro:macro name="wheel" params="prefix reflect_x reflect_y">

        <link name="${prefix}_wheel_link">

            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="${wheel_mass}" />
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <inertia
                    ixx="${1/12*wheel_mass*(3*(wheel_radius*wheel_radius)+(wheel_length*wheel_length))}"
                    iyy="${1/12*wheel_mass*(3*(wheel_radius*wheel_radius)+(wheel_length*wheel_length))}"
                    izz="${1/2*wheel_mass*(wheel_radius*wheel_radius)}"
                    ixy="0.0" iyz="0.0" ixz="0.0" />
            </inertial>

        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">

            <parent link="base_link" />
            <child link="${prefix}_wheel_link" />
            <origin
                xyz="${-reflect_x*(chassis_wheel_x_offset)} ${-reflect_y*(wheel_separation/2)} ${-(chassis_wheel_offset_height+(chassis_height/2))}"
                rpy="${pi/2} 0 0" />
            <axis xyz="0.0 0.0 -1.0" />
            <limit effort="0.56" velocity="12.56" />

        </joint>

    </xacro:macro>

    <!-- Base link -->
    <link name="base_link">
    </link>

    <!-- Frame -->
    <link name="frame_link">

        <visual>
            <origin
                xyz="${chassis_length/2} ${-chassis_breadth/2} ${chassis_height/2}"
                rpy="0 0 ${pi/2}" />
            <geometry>
                <mesh filename="file://$(find ostem_bringup)/urdf/meshes/chassis.stl" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <origin
                xyz="${chassis_length/2} ${-chassis_breadth/2} ${chassis_height/2}"
                rpy="0 0 ${pi/2}" />
            <geometry>
                <mesh filename="file://$(find ostem_bringup)/urdf/meshes/chassis.stl" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${wheel_mass}" />
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <inertia
                ixx="${1/12*wheel_mass*(3*(wheel_radius*wheel_radius)+(wheel_length*wheel_length))}"
                iyy="${1/12*wheel_mass*(3*(wheel_radius*wheel_radius)+(wheel_length*wheel_length))}"
                izz="${1/2*wheel_mass*(wheel_radius*wheel_radius)}"
                ixy="0.0" iyz="0.0" ixz="0.0" />
        </inertial>

    </link>

    <joint name="frame_joint" type="fixed">

        <parent link="base_link" />
        <child link="frame_link" />
        
    </joint>

    <!-- Wheels -->
    <xacro:wheel prefix="back_right" reflect_x="1" reflect_y="1" />
    <xacro:wheel prefix="back_left" reflect_x="1" reflect_y="-1" />
    <xacro:wheel prefix="front_right" reflect_x="-1" reflect_y="1" />
    <xacro:wheel prefix="front_left" reflect_x="-1" reflect_y="-1" />

</robot>