<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ostem">

    <!-- Adding friction -->
    <gazebo reference="base_link">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
    </gazebo>

    <gazebo reference="front_left_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <gazebo reference="front_right_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <gazebo reference="back_left_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <gazebo reference="back_right_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <!-- Plugins -->
    <gazebo>

        <!-- Joint state publisher -->
        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">

            <topic>/ostem/joint_states</topic>

            <joint_name>front_left_wheel_joint</joint_name>
            <joint_name>front_right_wheel_joint</joint_name>
            <joint_name>back_left_wheel_joint</joint_name>
            <joint_name>back_right_wheel_joint</joint_name>

        </plugin>

        <!-- Differential drive -->
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>
            <left_joint>back_left_wheel_joint</left_joint>
            <right_joint>back_right_wheel_joint</right_joint>

            <wheel_separation>${chassis_breadth+wheel_length}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <max_linear_accleration>1</max_linear_accleration>

            <topic>/ostem/cmd_vel</topic>
            <tf_topic>/ostem/tf</tf_topic>
            <odom_topic>/ostem/steering_odom</odom_topic>
            
            <frame_id>odom</frame_id>
            <child_frame_id>base_link</child_frame_id>
            <odom_publisher_frequency>50</odom_publisher_frequency>

        </plugin>

    </gazebo>

</robot>